### ISSUE TITLE
Close tabs from current domain

### ISSUE THREAD

**Issue by mos3abof** [mos3abof/firefox-power-close#2]
Create a menu item to close all tabs from currently active tab's domain name.

**Comment by mos3abof** [comment]
This issue is now resolved. A context menu entry has been added to close tabs from current domain in v 0.4.

**Comment by anewuser** [comment]
@mos3abof What about an optin to close all tabs from the current domain with a single click on the button (or another button for that)?

**Comment by mos3abof** [comment]
I am not a fan of doing things implicitly or "magically". I would like to do everything the python zen way:

"Explicit is better than implicit."

**Comment by anewuser** [comment]
@mos3abof I meant the extension button. Nothing would be done automatically. I just meant the same option that is already available in the context menu, but in the form of a button.

**Comment by mos3abof** [comment]
I understand that you mean the button. I would rather not make the button click do this, because we now have established that clicking on the button wil bring down a text box. 

I may consider adding more options when you click the icon, but this would require some time and some serious UI considerations. I am not the best at user experience, but I know that suddenly changing the button's behaviour is a bad decision. Also adding another button is cluttering.

One of the reasons I added the context menu was the complain from many users that they don't want to see the button, because they have other more important addons they want in there.

That being said, I am open to any ideas. If you think I understand you wrong, you can sketch up the UI modifications you propose and send them to me.

**Comment by anewuser** [comment]
I didn't propose to replace the current button completely for new or current users, but to add it as an *option*. You don't need to worry about the options UI because Firefox lets and encourages developers to use the preferences module buit-in in the Add-ons manager. See these examples from [Self-Destructing cookies](https://addons.mozilla.org/firefox/addon/self-destructing-cookies/): https://i.imgur.com/XyMqysw.png .

 If you kept a single button for both modes, the user would be free to toggle the "kill all from current domain" mode from this page. The current pop-up that appears when you click the button could have a link to it, or tell users to access the add-on preferences by themselves.

If you added a new separate button (the best choice in my opinion), it wouldn't be cluttering, because we are free to hide and add new buttons from the Customize View. All the buttons in this screenshot belong to a single extension, but the one above the bookmark star is the only one I see: https://i.imgur.com/6Bgv1eE.png

I actually use the [Menu Wizard extension](https://addons.mozilla.org/firefox/addon/s3menu-wizard/) to remove unused context menu entries, so I'm the opposite of those users and prefer to keep it clean. :) People who do like to use the menu option would still be free to keep using it instead of a button though. It's all about customization and choice.

**Comment by mos3abof** [comment]
I thank you for your detailed answer. You have given me some input to consider.

I will re-visit the issue in the nearest free time I get and see what that leads to.

Thanks for your feedback.
